export const SET_MESSAGES = 'SET_MESSAGES';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_IS_LISTENER = 'SET_IS_LISTENER';
export const SET_CURRENT_JOURNAL = 'SET_CURRENT_JOURNAL';
