// export default {
//   en: {
//     Language: 'Language:',
//     Home: 'Home',
//     password: 'Password',
//     signin: 'Sign in',
//     signup: 'Signup',
//     haveaccount: 'Don`t have an account yet ?',
//     user_name: 'Username',
//     name: 'Name',
//     your: 'Your',
//     member: 'Member',
//     Therapist: 'Therapist',
//     have_acount: 'Already have an acount ?',
//     for_you: 'For you',
//     counseling: 'Counseling',
//     connect_now: 'Connect now ',
//     dash: 'Dash',
//     feed: 'Feed',
//     journals: 'Journals',
//     message: 'Message',
//     your_posts: 'Your posts',
//     profile: 'Profile',
//     about: 'About',
//     likes: 'Likes',
//     dislikes: 'Dislikes',
//     favoret: 'Favourite',
//     songs: 'Songs',
//     books: 'Book',
//     friends: 'Friends',
//     change: 'Change',
//     edit: 'Edit',
//     Reply: 'Reply',
//     Replies: 'Replies ',
//     write_post: 'Write a post',
//     start_typing: 'Start typing',
//     send: 'Send',
//     book_time: 'Book a time',
//     price: 'Price',
//     Be_Reason: 'Be A Reason',
//     Be_Reason1: 'A reason someone is smiling and alive.',
//     Picture: 'Picture',
//     attach_here: 'Attach here',
//     bio: 'Bio',
//     write_bio: 'Write your bio',
//     expertise: 'Expertise',
//     Certificate: 'Certificate',
//   },
//   tu: {
//     Language: 'Dil:',
//     Home: 'Ev',
//     password: 'Parola',
//     signin: 'Oturum aç',
//     signup: 'Kaydol',
//     haveaccount: 'Henüz bir hesabınız yok',
//     user_name: 'Kullanıcı adı',
//     name: 'Isim',
//     your: 'Sizin ',
//     member: 'Üye',
//     Therapist: 'Terapist',
//     have_acount: 'Zaten hesabınız var mı ?',
//     for_you: 'Senin için',
//     counseling: 'Danışmanlık',
//     connect_now: 'şimdi Bağlan',
//     dash: 'Kısa çizgi',
//     feed: 'Besleme',
//     journals: 'Dergiler',
//     message: 'İleti',
//     your_posts: 'Sizin gönderileriniz',
//     profile: 'Profil',
//     about: 'Hakkında',
//     likes: 'Seviyor',
//     dislikes: 'Dislikes',
//     favoret: 'Favori ',
//     songs: 'şarkılar',
//     books: 'Kitabın',
//     friends: 'Arkadaşlar',
//     change: 'Değişiklik',
//     edit: 'Düzenle',
//     Reply: 'Cevap',
//     Replies: 'Cevaplar',
//     write_post: 'Bir gönderi yaz',
//     start_typing: 'Yazmaya başlayın',
//     send: 'Gönderme',
//     book_time: 'Bir zaman ayır',
//     price: 'Fiyat',
//     Be_Reason: 'Sebep Ol',
//     Be_Reason1: 'Birinin gülümsemesinin ve hayatta olmasının bir nedeni',
//     Picture: 'Resim',
//     attach_here: 'Buraya ekle',
//     bio: 'Biyo',
//     write_bio: 'Biyografini yaz',
//     expertise: 'Uzmanlık',
//     Certificate: 'Sertifika',
//   },
// };
